pipeline_name: "observability_correlation_pipeline"
stages:
  stage_1:
    description: "Process user experience data"
    input:
      type: "local_file"
      # TODO: set env variable for base path
      file_path: "/Users/rzhang/git/ODP-dynamic-data-pipeline/data/user_exp_{hour}.json"
    redis_mappings:
      write:
        redis_key_prefix: "trace_to_client"
        from_fields:
          key: "traceId"
          value: "clientId"
    output_file: "/Users/rzhang/git/ODP-dynamic-data-pipeline/output/user_exp_processed_{hour}.json"

  stage_2:
    description: "Enhance trace data"
    input:
      type: "s3"
      bucket: "demo-trace-bucket"
      prefix: "traces/{hour}/"
    redis_mappings:
      read:
        redis_key_prefix: "trace_to_client"
        key_field: "traceId"
      write:
        redis_key_prefix: "span_to_trace_client"
        from_fields:
          key: "spans.spanId"
          value: ["traceId", "clientId"]
    output_file: "/Users/rzhang/git/ODP-dynamic-data-pipeline/output/trace_processed_{hour}.json"

  stage_3:
    description: "Enhance log data"
    input:
      type: "s3"
      bucket: "demo-log-bucket"
      prefix: "logs/{hour}/"
    redis_mappings:
      read:
        redis_key_prefix: "span_to_trace_client"
        key_field: "spanId"
    output_file: "/Users/rzhang/git/ODP-dynamic-data-pipeline/output/log_processed_{hour}.json"
